### ISSUE TITLE
Erroneous tasks appear in Taskbar and don't correspond to actual windows

### ISSUE THREAD

**Issue by livinlicious** [lawand-dot-io/taskbar#37] opened 2024-03-25 14:26 UTC
When closing some window, their tasks stay in Taskbar, even though the windows are now closed.

Similarly, sometimes new tasks appear and they don't correspond with any of the app's windows.
 
This issue isn't always easily reproducible.

**Comment by lawand-dot-io** [comment] 2024-04-05 02:33
Thanks for the bug report. I tried using discord and I realized that they handle closing a window differently from other apps. When you close a discord window, it becomes marked as hidden (the same when you right click the app in Dock and select "Hide"). So, I have to figure out a way to work with discord, perhaps I would not show it's windows that are hidden. I can also make this a checkbox in preferences so users can choose to enable it or not.

As for other windows, I have seen that bug before and plan to fix it. The way it usually happens is that an item for a window is added to Taskbar even though there is no such window, so it doesn't correspond to an actual window. Do you remember which apps caused this issue for you? That could help me understand the bug. Cheers

**Comment by lawand-dot-io** [comment] 2024-05-21 17:47
The special case of discord window was split into a different bug https://github.com/lawand-dot-io/taskbar/issues/51

**Comment by lawand-dot-io** [comment] 2024-09-12 22:49
Closing this ticket as it hasn't been reproduced for me since v1.2.1

**Closed by lawand-dot-io** 2024-09-12 22:49 UTC
Labels: triaged
