### ISSUE TITLE
When minimized, unminimizing the Telegram native client for macOS reorders its window to the end of the list

### ISSUE THREAD

**Issue by fires3as0n** [lawand-dot-io/taskbar#74] opened 2024-08-19 19:29 UTC
**Describe the bug**
I have this problem with [Telegram native client for macOS](https://macos.telegram.org/) v11.0.2. Minimizing the app then unminimizing it by clicking on the app item in taskbar moves the app's task to the rightmost position regardless of manual sorting.

**To Reproduce**
1. Open Telegram native client for macOS app
2. Move the app to the left position in taskbar by dragging
3. Minimize the app by clicking on it in taskbar
4. Unminimize the app by clicking on it again

**Expected behavior**
App unminimizes and its task remains in the same position

**Actual behavior**
App unminimizes and moves to the rightmost position on the taskbar.

**Desktop (please complete the following information):**
 - Taskbar version [1.2.1]
 - OS: [12.6.2]
 - Chip [Intel i7]

**Additional context**
I can't think of it as a Telegram bug because taskbar should treat window from any app similar.

**Comment by lawand-dot-io** [comment] 2024-08-19 22:40
Hello. Thanks for the bug report. I tried it now with telegram and it didn't happen. Can you perhaps do a quick screen recording that shows the bug? that would be much appreciated

**Comment by fires3as0n** [comment] 2024-08-20 15:38
Here it is: https://www.youtube.com/watch?v=ad47m7Jc8Zs
Probably this is due to the fact that my MacOS version is quite old, when I will have plans to update I will check that again.

**Comment by lawand-dot-io** [comment] 2024-08-22 10:46
@fires3as0n ok I understand the bug a bit more now. It happens with the [Telegram native client for macOS](https://macos.telegram.org/) but not with the 
[Telegram Desktop](https://desktop.telegram.org/) app. That's why I wasn't able to reproduce it when I tried before.

The bug happens on all macOS versions, so it's not because yours is outdated. The reason this bug happens only with the Telegram native client for macOS is that this app for some reason closes its own window and reopens it whenever you unminimize it. This is non-standard behavior.

I doubt that I can fix this bug because its difficult to know whether the app is simply unminimized or actually closed then reopened.

Here are some indirect solutions:

- Right click the app in the Dock and select Assign to all desktops. This will keep its window at the start of Taskbar regardless of minimizing and unminimizing. The drawback is that if it is not minimized, it will be shown on all desktops
- Another idea is to never minimize this app and instead hide it using Taskbar by right clicking its window and selecting Hide. This is not so convenient unless you get used to it.
- You can also use the [Telegram Desktop](https://desktop.telegram.org/) app instead.

Feel free to ask if anything is not clear. Cheers

**Closed by lawand-dot-io** 2024-08-22 10:46 UTC

**Comment by fires3as0n** [comment] 2024-08-29 16:48
Thank you for the response, actually the only telegram app that I am able to install on my mac is this one  https://desktop.telegram.org the other one https://macos.telegram.org is simply not installing, but it is clear now that the problem is with app itself, not with the taskbar.

**Comment by lawand-dot-io** [comment] 2024-08-29 17:18
ah, that must be annoying. what about my other suggestions? anything works for you?

**Comment by fires3as0n** [comment] 2024-08-30 12:37
I have tried several, assigning to all desktops looks good. Also I find Telegram for MacOS inconvenient anyway (I have no idea why do they have different client than for Windows/Linux), so I just switched to as web version. This problem is solved but I have reported another much more severe one.
