### ISSUE TITLE
Taskbar item disappears if switching focus while in fullscreen (ie, watching a video)

### ISSUE THREAD

**Issue by derek1287** [lawand-dot-io/taskbar#90] opened 2024-10-02 22:28 UTC
**Describe the bug**
If you switch away from an app that is streaming something in fullscreen mode (ie, a youtube video), that app's taskbar item will disappear permanently.

**To Reproduce**
1. Watch a video on YouTube on your browser in fullscreen mode (ie, press F key to make the video itself fullscreen - not the app).
2. Press CMD+Tab to switch apps without first minimizing the video (or any other command to make a different app gain focus in front of the video)
3. Note that the browser showing the fullscreen video (now located in the background) will no longer have a taskbar item present.

**Expected behavior**
Browser playing the full-screen video in the background should still have a taskbar item.

**Desktop (please complete the following information):**
 - Taskbar version: 1.2.5
 - OS: macOS
 - Chip: Apple ARM chip

**Comment by lawand-dot-io** [comment] 2024-10-03 01:29
Hello. Thanks for the bug report. This is actually not a bug. The way Taskbar works at the moment is the only windows from the current Space are shown. When a video is fullscreened, it now has its own fullscreen Space along with the window it is a part of (so, the browser window). There has been a feature request to show windows from other spaces (https://github.com/lawand-dot-io/taskbar/discussions/39) but it was not implemented because the macOS API doesn't allow that in a reliable way. Sorry that I can't give more help on this. Feel free to reach out if you have other questions. Thanks

**Comment by lawand-dot-io** [comment] 2024-10-08 22:13
@derek1287 Closing the issue. Feel free to reopen it if you have further questions. Thanks :)

**Closed by lawand-dot-io** 2024-10-08 22:13 UTC
