### ISSUE TITLE
Unable to drag and drop tasks when using more than one monitor

### ISSUE THREAD

**Issue by Jon-edge** [lawand-dot-io/taskbar#38] opened 2024-03-28 21:00 UTC
**Describe the bug**
On an ultrawide screen, I'm unable to drag items more halfway across the taskbar, and many items can't be moved at all.

**To Reproduce**
1. Use an external ultrawide monitor as a primary display
2. Attempt to rearrange the items

**Expected behavior**
Rearrangement works for any number of spaces

**Screenshots**
https://github.com/lawand-dot-io/taskbar/assets/90650827/e942d4ac-d6e5-4783-aebb-05ed50dec50b

**Desktop (please complete the following information):**
 - Taskbar version 1.0.6
 - OS: 14.1.2 (23B92)
 - Chip M1 Max

**Additional context**
3 monitors, configration: [laptop] [primary ultrawide] [vertical secondary]

Resolution:
system_profiler SPDisplaysDataType | grep Resolution
          Resolution: 6720 x 2836 (primary external)
          Resolution: 3456 x 2234 Retina (laptop)
          Resolution: 2160 x 3840 (vertical external

**Comment by lawand-dot-io** [comment] 2024-03-29 00:07
Thanks for the bug report. First question is: do you have the "Displays have separate spaces" option enabled in system settings? Second, when you're using the monitor, are you also using another monitor (the macbook's monitor or a second monitor)?

**Comment by gohma231** [comment] 2024-04-15 14:34
I'm having the same issue. I do have "Displays have separate spaces" enabled.

**Comment by gohma231** [comment] 2024-04-16 22:11
I will also point out that this issue has nothing to do with having a widescreen monitor. I think better issue name would be: "Multiple monitors: Unable to rearrange items" or "Unable to rearrange items when multiple monitors connected."

**Comment by lawand-dot-io** [comment] 2024-04-19 07:46
@gohma231 thanks for the information. you have two monitors when the bug happens? or more than two?

**Comment by lawand-dot-io** [comment] 2024-06-07 20:15
This bug has been fixed in Taskbar version 1.2.1 which is now released. Closing the ticket.

**Closed by lawand-dot-io** 2024-06-07 20:15 UTC
Labels: triaged

**Comment by gavingt** [comment] 2025-06-18 02:04
I'm seeing the same (or similar) problem in the latest version:

**Describe the bug**
Task can't be dragged between monitors

**To Reproduce**
Steps to reproduce the behavior:
  Left-click and hold on a task in the Taskbar
  Attempt to drag the task to another window
  Task moves back to first monitor and gets inserted at the right-most position

**Expected behavior**
Task moves between the task bars on each monitor

**Desktop**
    Taskbar version 1.4.5
    OS: macOS 15.5
    Chip Apple M3 Pro

**Additional context**
I'm using "Displays have separate Spaces"
I'm using "Reorder tasks by drag and drop"

**Video**
[https://youtu.be/luPUtM7bLMM](https://youtu.be/luPUtM7bLMM)

**Comment by lawand-dot-io** [comment] 2025-06-18 22:06
@gavingt thanks for the great bug report. I created a separate ticket since this is a slightly different issue. check out my response there (https://github.com/lawand-dot-io/taskbar/issues/193). the short version is that this is not supported by Taskbar. cheers
